DECLARE
V_DEPT_ID DEPARTMENTS.DEPARTMENT_ID%TYPE := 10;
V_DEPT DEPARTMENTS%ROWTYPE;
BEGIN
SELECT * INTO V_DEPT FROM DEPARTMENTS WHERE DEPARTMENT_ID=V_DEPT_ID;
DBMS_OUTPUT.PUT_LINE('DEPARTMENT_ID' || ' ' || V_DEPT.DEPARTMENT_ID);
DBMS_OUTPUT.PUT_LINE('DEPARTMENT_NAME' || ' ' || V_DEPT.DEPARTMENT_NAME);
DBMS_OUTPUT.PUT_LINE('MANAGER_ID' || ' ' || V_DEPT.MANAGER_ID);
DBMS_OUTPUT.PUT_LINE('LOCATION_ID' || ' ' || V_DEPT.LOCATION_ID);
END;
