--select * from employees where employee_id=105;

DECLARE
V_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE :=105;
V_CURRENT_YEAR NUMBER :=TO_CHAR(SYSDATE,'YYYY');
V_HIRE_DATE NUMBER;
BEGIN
SELECT TO_CHAR(HIRE_DATE,'YYYY') INTO V_HIRE_DATE FROM EMPLOYEES WHERE EMPLOYEE_ID=V_EMP_ID;
V_HIRE_DATE := V_HIRE_DATE+2;
IF (V_HIRE_DATE < V_CURRENT_YEAR) THEN
DBMS_OUTPUT.PUT_LINE(V_EMP_ID || ' ' || 'ELIGIBLE FOR PROMOTION');
ELSE
DBMS_OUTPUT.PUT_LINE(V_EMP_ID || ' ' || 'NOT ELIGIBLE FOR PROMOTION');
END IF;
END;
