--select * from employees where employee_id=202;

DECLARE
V_COUNT_OF_EMP PLS_INTEGER;
V_EMPLOYEE_ID NUMBER(3) := 202;
V_COMMISSION_PCT EMPLOYEES.COMMISSION_PCT%TYPE := 0.1;
V_JOB_ID EMPLOYEES.JOB_ID%TYPE := 'MK_REP';
BEGIN
SELECT COUNT(EMPLOYEE_ID) INTO V_COUNT_OF_EMP FROM EMPLOYEES WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;
IF (V_COUNT_OF_EMP = 0) THEN
DBMS_OUTPUT.PUT_LINE(V_EMPLOYEE_ID || '   NOT EXIST');
ELSE
UPDATE EMPLOYEES SET COMMISSION_PCT=V_COMMISSION_PCT WHERE EMPLOYEE_ID=V_EMPLOYEE_ID;
DBMS_OUTPUT.PUT_LINE(V_EMPLOYEE_ID || '   HAS UPDATED COMMISSION_PCT SUCCESSFULLY');
END IF;
END;
