--SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID=100;

DECLARE
V_SALARY NUMBER(8,2);
V_TAX_AMOUNT NUMBER(8,2);
V_TAX_PERCENTAGE NUMBER(2);
V_EMPLOYEE_ID NUMBER(3):=100;
BEGIN
SELECT SALARY INTO V_SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID=V_EMPLOYEE_ID;
IF(V_SALARY > 15000) THEN
V_TAX_PERCENTAGE := 15 ;
ELSIF(V_SALARY < 15000 AND V_SALARY >=8000) THEN
V_TAX_PERCENTAGE := 10 ;
ELSE
V_TAX_PERCENTAGE := 0;
END IF;

V_TAX_AMOUNT := V_SALARY*V_TAX_PERCENTAGE*0.01;
DBMS_OUTPUT.PUT_LINE('EMPLOYEE HAS TO PAY TAX RS. ' || V_TAX_AMOUNT);
END;
