DECLARE
V_JOB_ID VARCHAR2(10) := 'FI_CLERK';
V_JOB_TITLE VARCHAR2(35) := 'Finance Clerk';
V_MIN_SALARY NUMBER(6) := 5000;
V_MAX_SALARY NUMBER(6) := 10000;
V_COUNT_OF_JOB PLS_INTEGER;
BEGIN
SELECT COUNT(JOB_ID) INTO V_COUNT_OF_JOB FROM JOBS WHERE JOB_ID=V_JOB_ID;
IF(V_COUNT_OF_JOB = 0) THEN
INSERT INTO JOBS VALUES(V_JOB_ID,V_JOB_TITLE,V_MIN_SALARY,V_MAX_SALARY);
DBMS_OUTPUT.PUT_LINE(V_JOB_ID || 'INSERTED SUCCESSFULLY');
ELSE
DBMS_OUTPUT.PUT_LINE(V_JOB_ID || '   ALREADY EXITS');
END IF;
END;
