--SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID=100;

DECLARE
V_SALARY NUMBER(8,2);
V_ELIGIBLE_SALARY CONSTANT NUMBER(6) :=8000;
V_EMPLOYEE_ID NUMBER(3):=100;
BEGIN
SELECT SALARY INTO V_SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID=V_EMPLOYEE_ID;
IF(V_SALARY>V_ELIGIBLE_SALARY) THEN
DBMS_OUTPUT.PUT_LINE('ELIGIBLE TO PAY TAX');
END IF;
END;
