DECLARE
V_COUNT_OF_EMP PLS_INTEGER;
BEGIN
FOR V_YEAR IN 1987 .. 2000 LOOP
SELECT COUNT(EMPLOYEE_ID) INTO V_COUNT_OF_EMP FROM EMPLOYEES WHERE TO_CHAR(hire_date,'yyyy')=V_YEAR;
DBMS_OUTPUT.PUT_LINE(V_YEAR || ' : ' || V_COUNT_OF_EMP);
END LOOP;
END;
