DECLARE
V_COUNT_OF_EMP PLS_INTEGER;
V_START_YEAR NUMBER := 1987;
V_END_YEAR NUMBER := TO_CHAR(SYSDATE,'YYYY');
BEGIN
LOOP
SELECT COUNT(EMPLOYEE_ID) INTO V_COUNT_OF_EMP FROM EMPLOYEES WHERE TO_CHAR(hire_date,'yyyy')=V_START_YEAR;
DBMS_OUTPUT.PUT_LINE(V_START_YEAR || ' : ' || V_COUNT_OF_EMP);
V_START_YEAR := V_START_YEAR + 1;
EXIT WHEN V_START_YEAR > V_END_YEAR;
END LOOP;
END;



